#!/usr/bin/env bash
# ==============================================================================
# AgentCanvas — Install Script
#
# Creates the canvas conda env from agentcanvas/environment.yaml, installs
# frontend npm deps, and generates agentcanvas/launch.sh.
#
# Usage:
#   bash scripts/install/install_agentcanvas.sh              # env name from YAML (agentcanvas)
#   bash scripts/install/install_agentcanvas.sh -n my-env    # override env name
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CANVAS_DIR="$REPO_ROOT/agentcanvas"
ENV_YAML="$CANVAS_DIR/environment.yaml"
FRONTEND_DIR="$CANVAS_DIR/frontend"
BACKEND_DIR="$CANVAS_DIR/backend"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[install/agentcanvas]${NC} $*"; }
info() { echo -e "${BLUE}[install/agentcanvas]${NC} $*"; }
fail() { echo -e "${RED}[install/agentcanvas]${NC} $*"; exit 1; }

# --------------- parse args ---------------------------------------------------
ENV_NAME=""
while getopts "n:" opt; do
  case $opt in
    n) ENV_NAME="$OPTARG" ;;
    *) fail "Usage: $0 [-n env_name]" ;;
  esac
done

# --------------- prerequisites ------------------------------------------------
log "Checking prerequisites..."

command -v conda >/dev/null 2>&1 || fail "conda not found. Install Miniforge/Miniconda first."

# Note: node/npm are bundled in environment.yaml (nodejs>=20). System-level
# node is not required — we verify the env-installed node after env creation.

eval "$(conda shell.bash hook 2>/dev/null)"

# --------------- resolve env name ---------------------------------------------
# If -n was given, use it; otherwise read name from the YAML.
if [ -z "$ENV_NAME" ]; then
  ENV_NAME=$(grep '^name:' "$ENV_YAML" | head -1 | awk '{print $2}')
fi
[ -n "$ENV_NAME" ] || fail "Could not determine env name from $ENV_YAML"

# Build the -n flag array (only used when overriding the YAML name)
YAML_NAME=$(grep '^name:' "$ENV_YAML" | head -1 | awk '{print $2}')
NAME_FLAG=()
if [ "$ENV_NAME" != "$YAML_NAME" ]; then
  NAME_FLAG=(-n "$ENV_NAME")
fi

# --------------- conda env ----------------------------------------------------
log "Setting up conda env: ${ENV_NAME}..."

# Must cd to agentcanvas/ so the YAML's `-r backend/requirements.txt` resolves.
if conda env list | grep -qw "$ENV_NAME"; then
  info "Env '${ENV_NAME}' already exists — updating."
  (cd "$CANVAS_DIR" && conda env update "${NAME_FLAG[@]}" -f "$ENV_YAML" --prune)
else
  info "Creating env '${ENV_NAME}' from ${ENV_YAML}..."
  (cd "$CANVAS_DIR" && conda env create "${NAME_FLAG[@]}" -f "$ENV_YAML")
fi

# --------------- activate env + verify node -----------------------------------
# Activate so the env-installed node/npm are on PATH for the frontend step.
# Conda's mkl/blas activate hooks reference variables without defaults, which
# trips bash `set -u`. Disable nounset around the activate call only.
set +u
conda activate "$ENV_NAME" || { set -u; fail "Failed to activate '$ENV_NAME'."; }
set -u

command -v node >/dev/null 2>&1 || fail "node not found in env — environment.yaml missing nodejs>=20?"
NODE_MAJOR=$(node --version | sed 's/v\([0-9]*\).*/\1/')
if [ "$NODE_MAJOR" -lt 18 ]; then
  fail "Env Node.js < 18 (found $(node --version)). Pin nodejs>=20 in environment.yaml."
fi
info "Using $(node --version) from env."

# --------------- frontend npm -------------------------------------------------
log "Installing frontend dependencies (npm)..."
(cd "$FRONTEND_DIR" && npm install --no-audit --no-fund)

# --------------- generate launch.sh -------------------------------------------
LAUNCH_FILE="$CANVAS_DIR/launch.sh"
log "Generating ${LAUNCH_FILE}..."

cat > "$LAUNCH_FILE" << 'LAUNCHER_EOF'
#!/usr/bin/env bash
# AgentCanvas launcher — backend :8000 + frontend :5173
# Generated by scripts/install/install_agentcanvas.sh — do not edit manually.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"
FRONTEND_DIR="$SCRIPT_DIR/frontend"

LAUNCHER_EOF

cat >> "$LAUNCH_FILE" << LAUNCHER_EOF
ENV_NAME="${ENV_NAME}"
LAUNCHER_EOF

cat >> "$LAUNCH_FILE" << 'LAUNCHER_EOF'

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

eval "$(conda shell.bash hook 2>/dev/null)"
conda activate "$ENV_NAME" 2>/dev/null || {
  echo -e "\033[0;31m[error]\033[0m Conda env '$ENV_NAME' not found. Run scripts/install/install_agentcanvas.sh first."
  exit 1
}

cleanup() {
  echo -e "\n${GREEN}Shutting down...${NC}"
  kill $BACKEND_PID $FRONTEND_PID 2>/dev/null || true
  wait $BACKEND_PID $FRONTEND_PID 2>/dev/null || true
  exit 0
}
trap cleanup SIGINT SIGTERM

echo -e "${GREEN}=== AgentCanvas ===${NC}"
echo -e "${BLUE}Conda env:${NC} $ENV_NAME"

echo -e "${BLUE}Starting backend on :8000...${NC}"
(cd "$BACKEND_DIR" && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000) &
BACKEND_PID=$!

echo -e "${BLUE}Starting frontend on :5173...${NC}"
(cd "$FRONTEND_DIR" && npx vite --host) &
FRONTEND_PID=$!

echo ""
echo -e "${GREEN}Backend:  http://localhost:8000${NC}"
echo -e "${GREEN}Frontend: http://localhost:5173${NC}"
echo -e "${GREEN}Swagger:  http://localhost:8000/docs${NC}"
echo ""

wait $BACKEND_PID $FRONTEND_PID
LAUNCHER_EOF

chmod +x "$LAUNCH_FILE"

# --------------- done ---------------------------------------------------------
log "Done! Env: ${ENV_NAME}"
echo -e "  ${GREEN}Launch:${NC} bash agentcanvas/launch.sh"
